FROM docker.io/cloudflare/sandbox:0.5.0

# On a Mac with Apple Silicon, you might need to specify the platform:
# FROM --platform=linux/arm64 docker.io/cloudflare/sandbox:0.5.0

# Required during local development to access exposed ports
EXPOSE 8080
