/* eslint-disable */
// This file will be auto-generated by Wrangler when you run `wrangler types`
// For now, this provides basic type definitions for the minimal example
declare namespace Cloudflare {
	interface Env {
		Sandbox: DurableObjectNamespace<import("./src/index").Sandbox>;
	}
}
interface Env extends Cloudflare.Env {}
