# This image is unique to this repo, and you'll never need it.
# Whenever you're integrating with sandbox SDK in your own project,
# you should use the official image instead:
# FROM docker.io/cloudflare/sandbox:0.4.1
FROM cloudflare/sandbox-test:0.4.1

# On a mac, you might need to actively pick up the
# arm64 build of the image.
# FROM --platform=linux/arm64 cloudflare/sandbox-test:0.1.3

# Expose the ports you want to expose
EXPOSE 8080
EXPOSE 3001
